# Generated by Django 5.2.5 on 2025-08-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('type', models.CharField(default='visit', max_length=20)),
                ('detail', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClickCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(default='education', max_length=50)),
                ('object_id', models.IntegerField()),
                ('click_count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
