# Generated by Django 5.2.5 on 2025-08-22 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=200)),
                ('sdg_number', models.IntegerField()),
                ('target_code', models.CharField(max_length=10)),
                ('target_description', models.TextField()),
                ('reference1', models.TextField(blank=True, null=True)),
                ('reference2', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Keyword Resource',
                'verbose_name_plural': 'Keyword Resources',
                'db_table': 'keyword_resources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeywordLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywords.keywordresource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'keyword_likes',
                'unique_together': {('user', 'keyword_resource')},
            },
        ),
    ]
