# Generated by Django 5.2.6 on 2025-09-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
                'db_table': 'sdgtargets_references',
                'ordering': ['id'],
            },
        ),
    ]
