# Generated by Django 5.2.6 on 2025-09-09 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('notification_type', 'team_invitation'), ('status', 'pending')), fields=('recipient', 'notification_type', 'status'), name='unique_pending_team_invitation'),
        ),
    ]
