# Generated by Django 5.2.6 on 2025-09-09 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_unique_pending_team_invitation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='unique_pending_team_invitation',
        ),
    ]
