# Generated by Django 5.2.6 on 2025-09-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notification_unique_pending_team_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('team_invitation', 'Team Invitation'), ('form_review_request', 'Form Review Request'), ('form_review_completed', 'Form Review Completed')], default='team_invitation', max_length=50),
        ),
    ]
