# Generated by Django 5.2.6 on 2025-09-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('team_invitation', 'Team Invitation'), ('form_review_request', 'Form Review Request'), ('form_review_completed', 'Form Review Completed'), ('form_review_status_update', 'Form Review Status Update')], default='team_invitation', max_length=50),
        ),
    ]
