# Generated by Django 5.2.5 on 2025-08-22 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, db_column='Title', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('aims', models.TextField(blank=True, db_column='Aims', null=True)),
                ('learning_outcome_expecting_outcome_field', models.TextField(blank=True, db_column='Learning outcome( Expecting outcome)', null=True)),
                ('type_label', models.CharField(blank=True, db_column='Type label', max_length=50, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=50, null=True)),
                ('organization', models.CharField(blank=True, db_column='Organization', max_length=128, null=True)),
                ('year', models.CharField(blank=True, db_column='Year', max_length=50, null=True)),
                ('sdgs_related', models.TextField(blank=True, db_column='SDGs related', null=True)),
                ('related_to_which_discipline', models.CharField(blank=True, db_column='Related to which discipline', max_length=128, null=True)),
                ('useful_for_which_industries', models.TextField(blank=True, db_column='Useful for which industries', null=True)),
                ('source', models.TextField(blank=True, db_column='Source', null=True)),
                ('link', models.TextField(blank=True, db_column='Link', null=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('column14', models.IntegerField(blank=True, db_column='Column14', null=True)),
                ('column15', models.CharField(blank=True, db_column='Column15', max_length=50, null=True)),
                ('column16', models.CharField(blank=True, db_column='Column16', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Education Resource',
                'verbose_name_plural': 'Education Resources',
                'db_table': 'education_db',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LikedEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'education_id')},
            },
        ),
    ]
