# Generated by Django 5.2.5 on 2025-08-22 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('action', 'Action'), ('education', 'Education'), ('blank', 'Blank'), ('ida', 'IDA')], default='action', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('locked', 'Locked'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_anonymous', models.BooleanField(default=False)),
                ('allow_multiple_submissions', models.BooleanField(default=False)),
                ('require_login', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_template', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('max_responses', models.PositiveIntegerField(blank=True, null=True)),
                ('is_collaborative', models.BooleanField(default=True)),
                ('current_editors', models.JSONField(default=list)),
                ('last_edit_at', models.DateTimeField(auto_now=True)),
                ('edit_version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_forms', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='team.team')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FormContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('aims', models.TextField(blank=True)),
                ('learning_outcomes', models.TextField(blank=True)),
                ('type_label', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('organization', models.CharField(blank=True, max_length=128)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('sdgs_related', models.TextField(blank=True)),
                ('related_discipline', models.CharField(blank=True, max_length=128)),
                ('useful_industries', models.TextField(blank=True)),
                ('source', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('actions', models.TextField(blank=True)),
                ('action_detail', models.TextField(blank=True)),
                ('level', models.IntegerField(blank=True, default=None, null=True)),
                ('individual_organization', models.IntegerField(blank=True, default=None, null=True)),
                ('location_specific', models.TextField(blank=True)),
                ('related_industry', models.TextField(blank=True)),
                ('digital_actions', models.BooleanField(default=False)),
                ('source_descriptions', models.TextField(blank=True)),
                ('award', models.BooleanField(default=False)),
                ('source_links', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('award_descriptions', models.TextField(blank=True)),
                ('free_content', models.TextField(blank=True)),
                ('designer_names', models.CharField(blank=True, max_length=200)),
                ('current_role_affiliation', models.CharField(blank=True, max_length=200)),
                ('impact_project_name', models.CharField(blank=True, max_length=100)),
                ('main_challenge', models.TextField(blank=True)),
                ('project_description', models.TextField(blank=True)),
                ('selected_sdgs', models.JSONField(blank=True, default=list)),
                ('impact_types', models.JSONField(blank=True, default=dict)),
                ('project_importance', models.TextField(blank=True)),
                ('existing_example', models.TextField(blank=True)),
                ('implementation_step1', models.TextField(blank=True)),
                ('implementation_step2', models.TextField(blank=True)),
                ('implementation_step3', models.TextField(blank=True)),
                ('implementation_step4', models.TextField(blank=True)),
                ('implementation_step5', models.TextField(blank=True)),
                ('implementation_step6', models.TextField(blank=True)),
                ('resources_partnerships', models.TextField(blank=True)),
                ('skills_capabilities', models.TextField(blank=True)),
                ('impact_avenues', models.TextField(blank=True)),
                ('risks_inhibitors', models.TextField(blank=True)),
                ('mitigation_strategies', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='form.form')),
            ],
        ),
        migrations.CreateModel(
            name='FormEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('change_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], default='update', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='form.form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormEditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cursor_position', models.IntegerField(default=0)),
                ('selection_start', models.IntegerField(blank=True, null=True)),
                ('selection_end', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_sessions', to='form.form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['team', 'status'], name='form_form_team_id_28b42c_idx'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['team', 'type'], name='form_form_team_id_074135_idx'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['created_by'], name='form_form_created_bf8e30_idx'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['-created_at'], name='form_form_created_d92e47_idx'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['-updated_at'], name='form_form_updated_fdc581_idx'),
        ),
        migrations.AddIndex(
            model_name='formcontent',
            index=models.Index(fields=['form', 'version'], name='form_formco_form_id_f0b714_idx'),
        ),
        migrations.AddIndex(
            model_name='formedithistory',
            index=models.Index(fields=['form', 'timestamp'], name='form_formed_form_id_169d60_idx'),
        ),
        migrations.AddIndex(
            model_name='formedithistory',
            index=models.Index(fields=['form', 'field_name'], name='form_formed_form_id_e3d151_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formeditsession',
            unique_together={('form', 'user')},
        ),
    ]
