# Generated by Django 5.2.6 on 2025-09-17 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='review_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='form',
            name='review_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted_for_review', 'Submitted for Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=25),
        ),
        migrations.AddField(
            model_name='form',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form',
            name='submitted_for_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
