# Generated by Django 5.2.6 on 2025-09-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_form_review_comments_form_review_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formcontent',
            name='location_specific',
        ),
    ]
