# Generated by Django 5.2.6 on 2025-09-20 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_remove_formcontent_location_specific'),
        ('team', '0002_alter_team_max_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='team.team'),
        ),
    ]
