# Generated by Django 5.2.5 on 2025-08-22 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionDb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actions', models.TextField(blank=True, db_column='Actions', null=True)),
                ('action_detail', models.TextField(blank=True, db_column='Action detail', null=True)),
                ('field_sdgs', models.CharField(blank=True, db_column=' SDGs', max_length=50, null=True)),
                ('level', models.IntegerField(blank=True, db_column='Level', null=True)),
                ('individual_organization', models.IntegerField(blank=True, db_column='Individual/Organization', null=True)),
                ('location_specific_actions_org_onlyonly_field', models.TextField(blank=True, db_column='Location (specific actions/org onlyonly)', null=True)),
                ('related_industry_org_only_field', models.TextField(blank=True, db_column='Related Industry (org only)', null=True)),
                ('digital_actions', models.IntegerField(blank=True, db_column='Digital actions', null=True)),
                ('source_descriptions', models.TextField(blank=True, db_column='Source descriptions', null=True)),
                ('award', models.IntegerField(blank=True, db_column='Award', null=True)),
                ('source_links', models.TextField(blank=True, db_column='Source Links', null=True)),
                ('additional_notes', models.TextField(blank=True, db_column='Additional Notes', null=True)),
                ('column15', models.CharField(blank=True, db_column='Column15', max_length=50, null=True)),
                ('award_descriptions', models.TextField(blank=True, db_column='Award descriptions', null=True)),
            ],
            options={
                'verbose_name': 'Action Resource',
                'verbose_name_plural': 'Action Resources',
                'db_table': 'action_db',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LikedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liked Action',
                'verbose_name_plural': 'Liked Actions',
                'db_table': 'liked_action',
                'unique_together': {('user', 'action_id')},
            },
        ),
    ]
