# Generated by Django 5.2.6 on 2025-09-11 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actiondb',
            options={'ordering': ['-id'], 'verbose_name': 'Action Resource', 'verbose_name_plural': 'Action Resources'},
        ),
    ]
