# Generated by Django 5.2.6 on 2025-09-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_alter_actiondb_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiondb',
            name='level',
            field=models.TextField(blank=True, db_column='Level', null=True),
        ),
    ]
